# Generated by Django 3.2 on 2024-12-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weekend_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('public_holiday_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('deliveries', models.IntegerField(default=0)),
                ('summary_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(null=True)),
                ('is_public_holiday', models.BooleanField(default=False)),
                ('deliveries', models.IntegerField(default=0)),
                ('login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('logout_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user')),
            ],
        ),
    ]
