# Generated by Django 5.1.3 on 2024-12-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_auto_20241202_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="shift_length_mins",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activity",
            name="logout_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
