# Generated by Django 5.1.3 on 2024-12-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_app",
            "0003_activity_last_updated_at_activity_shift_length_mins_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyValueStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
            ],
        ),
    ]
