# Generated by Django 5.1.3 on 2024-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_keyvaluestore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyvaluestore",
            name="value",
            field=models.CharField(max_length=256),
        ),
    ]
