# Generated by Django 5.1.3 on 2024-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_alter_keyvaluestore_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="hours_worked",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
