# Generated by Django 5.1.4 on 2024-12-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_activity_hours_worked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="shift_length_mins",
        ),
        migrations.AlterField(
            model_name="activity",
            name="login_timestamp",
            field=models.DateTimeField(),
        ),
    ]
