# Generated by Django 5.1.3 on 2024-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_remove_activity_shift_length_mins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="shift_length_mins",
            field=models.IntegerField(default=0),
        ),
    ]
