# Generated by Django 5.1.3 on 2024-12-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0008_activity_shift_length_mins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="login_timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
