# Generated by Django 5.1.3 on 2024-12-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0009_alter_activity_login_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="hours_worked",
        ),
    ]
