# Generated by Django 5.1.4 on 2025-02-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0010_remove_activity_hours_worked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="login_timestamp",
            field=models.DateTimeField(),
        ),
    ]
