# Generated by Django 5.1.4 on 2025-02-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0011_alter_activity_login_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="login_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
