# Generated by Django 5.2 on 2025-04-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0012_alter_activity_login_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("location_street", models.CharField(max_length=255, null=True)),
                (
                    "location_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "location_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                ("store_pin", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_app.store",
            ),
        ),
        migrations.CreateModel(
            name="StoreUserAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_access",
                        to="auth_app.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_access",
                        to="auth_app.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "store")},
            },
        ),
    ]
