# Generated by Django 5.2 on 2025-04-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0016_update_user_pin_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_pin",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pin",
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
