# Generated by Django 5.2 on 2025-04-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0016_update_user_pin_uniqueness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pin",
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
