# Generated by Django 5.2 on 2025-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0017_user_is_hidden_alter_store_store_pin_alter_user_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="allowable_clocking_dist_m",
            field=models.PositiveIntegerField(
                default=500, help_text="Allowed clock-in distance in meters"
            ),
        ),
    ]
