# Generated by Django 5.2 on 2025-04-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0018_store_allowable_clocking_dist_m"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="employee_id",
            new_name="employee",
        ),
        migrations.RemoveField(
            model_name="user",
            name="clocked_in",
        ),
    ]
