# Generated by Django 5.2 on 2025-05-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0019_rename_employee_id_activity_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_setup",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
