# Generated by Django 5.2 on 2025-05-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0020_user_is_setup_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storeuseraccess",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="storeuseraccess",
            constraint=models.UniqueConstraint(
                fields=("user", "store"), name="unique_user_store"
            ),
        ),
    ]
