# Generated by Django 5.2 on 2025-05-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0021_alter_storeuseraccess_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KeyValueStore",
        ),
        migrations.DeleteModel(
            name="Summary",
        ),
    ]
