# Generated by Django 5.2 on 2025-05-16 15:52

import auth_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0022_delete_keyvaluestore_delete_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short subject or headline for the notification",
                        max_length=200,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system_alert", "System Alert"),
                            ("manager_note", "Manager Note"),
                            ("schedule_change", "Schedule Change"),
                            ("general", "General"),
                            ("emergency", "Emergency"),
                        ],
                        default="general",
                        help_text="The type of notification",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        default=auth_app.models.notification_default_expires_on,
                        help_text="Optional expiration date after which the notification is considered inactive",
                        null=True,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to="auth_app.user",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: If set, limits recipients to this store",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth_app.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "notification")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="targeted_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Used when sending to specific users (USE NOTIFICATION RECEIPTS TO SET)",
                related_name="notifications",
                through="auth_app.NotificationReceipt",
                to="auth_app.user",
            ),
        ),
    ]
