# Generated by Django 5.2 on 2025-05-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0023_notification_notificationreceipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="broadcast_to_store",
            field=models.BooleanField(
                default=False,
                help_text="If True, broadcast to all users in the store. Used only if `store` is set.",
            ),
        ),
    ]
