# Generated by Django 5.2 on 2025-05-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0025_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationreceipt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_receipts",
                to="auth_app.user",
            ),
        ),
    ]
