# Generated by Django 5.2 on 2025-05-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0026_alter_notificationreceipt_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("system_alert", "System Alert"),
                    ("automatic_alert", "Automatic Alert"),
                    ("admin_note", "Admin Note"),
                    ("manager_note", "Manager Note"),
                    ("schedule_change", "Schedule Change"),
                    ("general", "General"),
                    ("emergency", "Emergency"),
                ],
                default="general",
                help_text="The type of notification",
                max_length=50,
            ),
        ),
    ]
