# Generated by Django 5.2 on 2025-05-20 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0027_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="auth_app.user",
            ),
        ),
    ]
