# Generated by Django 5.2.1 on 2025-05-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0028_alter_activity_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
