# Generated by Django 5.2.1 on 2025-05-27 06:59

import auth_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0029_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="logout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="logout_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="expires_on",
            field=models.DateField(
                default=auth_app.models.notification_default_expires_on,
                help_text="Optional expiration date after which the notification is considered inactive",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_notifications",
                to="auth_app.user",
            ),
        ),
    ]
