# Generated by Django 5.2.1 on 2025-05-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0030_alter_activity_logout_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="broadcast_to_store",
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient_group",
            field=models.CharField(
                choices=[
                    ("store_managers", "Store Managers Only"),
                    (
                        "store_employees",
                        "Store Employees (Every active user in your selected store)",
                    ),
                    ("site_admins", "Site Administrators"),
                    ("all_users", "All Active Users (Site-wide)"),
                    ("all_managers", "All Active Managers (Site-wide)"),
                    ("individual", "Individual User"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="The type of the receipient group",
                max_length=50,
            ),
        ),
    ]
