# Generated by Django 5.2.1 on 2025-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0031_remove_notification_broadcast_to_store_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="login_time",
            field=models.DateTimeField(db_index=True),
        ),
    ]
