# Generated by Django 5.2.1 on 2025-06-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0033_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
