# Generated by Django 5.2.2 on 2025-06-12 10:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0034_alter_shift_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="role",
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=210)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "colour_hex",
                    models.CharField(
                        default="#EEEEEE",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g., #AABBCC)",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="auth_app.store",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "name"), name="unique_store_role"
                    )
                ],
            },
        ),
    ]
