# Generated by Django 5.2.2 on 2025-06-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0035_remove_shift_role_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="auth_app.role",
            ),
        ),
    ]
