# Generated by Django 5.2.2 on 2025-06-15 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0036_shift_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_exceptions",
                        to="auth_app.activity",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_exceptions",
                        to="auth_app.shift",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("shift", None), _negated=True),
                        fields=("shift",),
                        name="unique_shift_exception",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("activity", None), _negated=True),
                        fields=("activity",),
                        name="unique_activity_exception",
                    ),
                ],
            },
        ),
    ]
