# Generated by Django 5.2.2 on 2025-06-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0037_shiftexception"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftexception",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
