# Generated by Django 5.2.2 on 2025-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0038_alter_shiftexception_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shiftexception",
            old_name="approved",
            new_name="is_approved",
        ),
        migrations.AddField(
            model_name="shift",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shiftexception",
            name="reason",
            field=models.CharField(
                choices=[
                    ("bad_clocking", "Incorrectly Clocked"),
                    ("missed_shift", "Missed Shift"),
                    ("no_shift", "No Shift"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="The type of Shift Exception",
                max_length=25,
            ),
        ),
    ]
