# Generated by Django 5.2.2 on 2025-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0039_rename_approved_shiftexception_is_approved_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["store", "date", "start_time"],
                name="auth_app_sh_store_i_d61c13_idx",
            ),
        ),
    ]
