# Generated by Django 5.2.2 on 2025-06-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0040_shift_auth_app_sh_store_i_d61c13_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={"ordering": ["store", "date", "start_time"]},
        ),
    ]
