# Generated by Django 5.2.2 on 2025-06-20 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0041_alter_shift_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="colour_hex",
            field=models.CharField(
                default="#adb5bd",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color code (e.g., #AABBCC)",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
    ]
