# Generated by Django 5.2.2 on 2025-06-28 05:48

from django.db import migrations
from django.db.models import Count


def remove_duplicate_shifts(apps, schema_editor):
    Shift = apps.get_model("auth_app", "Shift")

    from collections import defaultdict

    # Group shifts by (employee, store, date)
    duplicates = (
        Shift.objects
        .values("employee", "store", "date")
        .annotate(shift_count=Count("id"))
        .filter(shift_count__gt=1)
    )

    for dup in duplicates:
        # Get all shifts for this (employee, store, date), ordered by created_at
        shifts = list(
            Shift.objects
            .filter(
                employee=dup["employee"],
                store=dup["store"],
                date=dup["date"]
            )
            .order_by("created_at")
        )

        # Keep the first, delete the rest
        for shift in shifts[1:]:
            shift.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0042_alter_role_colour_hex"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_shifts),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("employee", "store", "date")},
        ),
    ]