# Generated by Django 5.2.2 on 2025-06-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0043_alter_shift_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_clocking_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="store",
            name="is_health_safety_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
