# Generated by Django 5.2.2 on 2025-06-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0043_alter_shift_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("employee", "store", "date", "start_time")},
        ),
        migrations.AddField(
            model_name="shift",
            name="comment",
            field=models.TextField(blank=True, default="", max_length=1500),
        ),
        migrations.AddField(
            model_name="shift",
            name="is_unscheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, default="", max_length=750),
        ),
    ]
