# Generated by Django 5.2.2 on 2025-06-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0044_alter_shift_unique_together_shift_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="comment",
            field=models.TextField(blank=True, default="", max_length=1500, null=True),
        ),
    ]
