# Generated by Django 5.2.2 on 2025-07-02 10:14

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def deduplicate_shiftexceptions(apps, schema_editor):
    ShiftException = apps.get_model("auth_app", "ShiftException")

    # Remove duplicate shift-related exceptions
    duplicate_shifts = (
        ShiftException.objects.exclude(shift=None)
        .values("shift")
        .annotate(c=Count("id"))
        .filter(c__gt=1)
    )

    for entry in duplicate_shifts:
        shift_id = entry["shift"]
        # Keep the most recent one (by created_at), delete the rest
        to_delete = ShiftException.objects.filter(shift_id=shift_id).order_by("-created_at")[1:]
        to_delete.delete()

    # Remove duplicate activity-related exceptions
    duplicate_activities = (
        ShiftException.objects.exclude(activity=None)
        .values("activity")
        .annotate(c=Count("id"))
        .filter(c__gt=1)
    )

    for entry in duplicate_activities:
        activity_id = entry["activity"]
        # Keep the most recent one (by created_at), delete the rest
        to_delete = ShiftException.objects.filter(activity_id=activity_id).order_by("-created_at")[1:]
        to_delete.delete()



class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0045_alter_shift_comment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shiftexception",
            name="unique_shift_exception",
        ),
        migrations.RemoveConstraint(
            model_name="shiftexception",
            name="unique_activity_exception",
        ),
        migrations.RunPython(deduplicate_shiftexceptions, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="shiftexception",
            name="activity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_shiftexception",
                to="auth_app.activity",
            ),
        ),
        migrations.AlterField(
            model_name="shiftexception",
            name="shift",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_shiftexception",
                to="auth_app.shift",
            ),
        ),
    ]
