# Generated by Django 5.2.2 on 2025-07-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0046_remove_shiftexception_unique_shift_exception_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_manager",
        ),
        migrations.AddField(
            model_name="storeuseraccess",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
