# Generated by Django 5.2.2 on 2025-07-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0047_remove_user_is_manager_storeuseraccess_is_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_scheduling_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
