# Generated by Django 5.2.2 on 2025-07-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0048_store_is_scheduling_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("swap_request", "Swap Shift Request"),
                            ("cover_request", "Cover Shift Request"),
                            ("BID_request", "New Shift Bid"),
                        ],
                        default="BID_request",
                        help_text="The type of Shift Request",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_shift_requests",
                        to="auth_app.user",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_requests",
                        to="auth_app.shift",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_shift_requests",
                        to="auth_app.store",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_shift_requests",
                        to="auth_app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
