# Generated by Django 5.2.2 on 2025-07-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0049_shiftrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrequest",
            name="shift",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_request",
                to="auth_app.shift",
            ),
        ),
        migrations.AlterField(
            model_name="shiftrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("swap_request", "Swap Shift Request"),
                    ("cover_request", "Cover Shift Request"),
                    ("bid_request", "New Shift Bid"),
                ],
                default="bid_request",
                help_text="The type of Shift Request",
                max_length=20,
            ),
        ),
    ]
