# Generated by Django 5.2.2 on 2025-08-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0049_alter_shiftrequest_shift_alter_shiftrequest_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftrequest",
            name="shift_details_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="shiftrequest",
            name="shift_details_end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="shiftrequest",
            name="shift_details_original_employee_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shiftrequest",
            name="shift_details_role_name",
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name="shiftrequest",
            name="shift_details_start_time",
            field=models.TimeField(null=True),
        ),
    ]
