# Generated by Django 5.2.2 on 2025-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0049_shiftrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("swap_request", "Swap Shift Request"),
                    ("cover_request", "Cover Shift Request"),
                    ("bid_request", "New Shift Bid"),
                ],
                default="bid_request",
                help_text="The type of Shift Request",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="shiftrequest",
            index=models.Index(
                fields=["status", "requester_id"], name="auth_app_sh_status_de66a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftrequest",
            index=models.Index(
                fields=["status", "target_user_id"],
                name="auth_app_sh_status_16c4e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftrequest",
            index=models.Index(
                fields=["status", "store_id"], name="auth_app_sh_status_8b171d_idx"
            ),
        ),
    ]
