# Generated by Django 5.2.2 on 2025-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0050_alter_shiftrequest_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="employees_can_view_storewide_roster",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, associated non-hidden, active users can view the full weekly roster.",
            ),
        ),
    ]
