# Generated by Django 5.2.2 on 2025-08-06 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0050_shiftrequest_shift_details_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrequest",
            name="shift",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_request",
                to="auth_app.shift",
            ),
        ),
    ]
