# Generated by Django 5.2.6 on 2025-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0050_alter_shiftrequest_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_global_shift_view_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, all employees can see everyones shift.",
            ),
        ),
    ]
