# Generated by Django 5.2.2 on 2025-08-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0051_alter_shiftrequest_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrequest",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_requests",
                to="auth_app.shift",
            ),
        ),
    ]
