# Generated by Django 5.2.7 on 2025-11-05 13:17

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_app",
            "0051_rename_auth_app_shiftreq_status_requester_idx_shiftreq_status_requester_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatingShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_weekday", models.PositiveSmallIntegerField()),
                ("end_time", models.TimeField()),
                (
                    "active_weeks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "Week 1"),
                                (2, "Week 2"),
                                (3, "Week 3"),
                                (4, "Week 4"),
                            ]
                        ),
                        help_text="Which weeks in the 4-week cycle this shift is active",
                        size=4,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", max_length=1500, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeating_shifts",
                        to="auth_app.user",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repeating_shifts",
                        to="auth_app.role",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeating_shifts",
                        to="auth_app.store",
                    ),
                ),
            ],
            options={
                "ordering": ["store", "start_weekday", "start_time"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["active_weeks"], name="active_weeks_gin_idx"
                    ),
                    models.Index(
                        fields=["store", "start_weekday", "start_time"],
                        name="store_day_time_idx",
                    ),
                    models.Index(fields=["employee"], name="employee_idx"),
                ],
            },
        ),
    ]
