# Generated by Django 5.2.2 on 2025-12-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0052_repeatingshift"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_repeating_shifts_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
