# Generated by Django 5.2.2 on 2025-08-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0052_alter_shiftrequest_shift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftrequest",
            name="shift_details_date",
        ),
        migrations.RemoveField(
            model_name="shiftrequest",
            name="shift_details_end_time",
        ),
        migrations.RemoveField(
            model_name="shiftrequest",
            name="shift_details_original_employee_name",
        ),
        migrations.RemoveField(
            model_name="shiftrequest",
            name="shift_details_role_name",
        ),
        migrations.RemoveField(
            model_name="shiftrequest",
            name="shift_details_start_time",
        ),
        migrations.AlterField(
            model_name="shiftrequest",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_requests",
                to="auth_app.shift",
            ),
        ),
    ]
