"""
Django settings for clock_in_system project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path


def str_to_bool(value):
    """Convert environment variable string to boolean."""
    return value.lower() in ["true", "1", "yes"]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_URL = "/manager_login/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-7!xp6vs%4*%t5bqw*5a%l1@#0(8k-zjr14x0%c3^ey&k4qr@5c",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# Get the BASE_URL from the environment
BASE_URL = os.getenv(
    "BASE_URL", "http://localhost:8000"
)  # Default to localhost if not set

# Parse ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")

# Cookies
SESSION_COOKIE_AGE = 604800  # 7 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = (
    False  # Set to True if you want the session to end on browser close
)

# Secure cookie settings
CSRF_USE_SESSIONS = False  # Disabled as it can break for some users who disable presistent sessions/cookies.
CSRF_COOKIE_AGE = 604800
CSRF_COOKIE_SECURE = str_to_bool(
    os.getenv("CSRF_COOKIE_SECURE", "False")
)  # Use True in production to send cookies over HTTPS only
CSRF_COOKIE_HTTPONLY = True  # Default is False; True prevents JavaScript access
CSRF_COOKIE_SAMESITE = os.getenv(
    "CSRF_COOKIE_SAMESITE", "Lax"
)  # Can be 'Lax', 'Strict', or 'None'
CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://localhost,http://127.0.0.1:8000,http://127.0.0.1",
).split(",")

# CORS settings
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:8000,http://localhost,http://127.0.0.1:8000,http://127.0.0.1",
).split(",")
CORS_TRUSTED_ORIGINS = os.getenv(
    "CORS_TRUSTED_ORIGINS",
    "http://localhost:8000,http://localhost,http://127.0.0.1:8000,http://127.0.0.1",
).split(",")
CORS_ALLOW_CREDENTIALS = False  # App currently doesnt use any authorisation cross-site (SET TO TRUE IF ENDPOINTS ON DIFF DOMAINS I.E. API ON api.domain.com -- then withCredentials is needed for js ajax requests)
CORS_PREFLIGHT_MAX_AGE = 43200  # Cache for 12 hours
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "api",
    "auth_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "clock_in_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "auth_app.base_url_context_processor.base_url",
            ],
        },
    },
]

WSGI_APPLICATION = "clock_in_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "clock_in_system"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "InsEcuR3Pa55w0Rd"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Django cache to store the more temporary info (i.e. public holiday checks)
if DEBUG:  # Use memory for development (saves the file permission errors)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "django_cache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": "/app/django_cache",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TZ", "Australia/Perth")

USE_I18N = True

USE_TZ = True


# This is used for public holiday information: (https://date.nager.at/)
COUNTRY_CODE = "AU"
COUNTRY_SUBDIV_CODE = "WA"
UTC_OFFSET = "8"  # For UTC+8


# Rounding amount for calculating true shift length
SHIFT_ROUNDING_MINS = 15  # Default is 15min

# How long a user must wait between finishing a shift and starting a new one
START_NEW_SHIFT_TIME_DELTA_THRESHOLD_MINS = 30  # Default is 30m

# How long a user must wait between starting a shift and finishing it
FINISH_SHIFT_TIME_DELTA_THRESHOLD_MINS = 15  # Default is 15m

# Determine maximum possible dump size for db queries (i.e. employee details list)
MAX_DATABASE_DUMP_LIMIT = 150


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"  # Adds hash to static files to ensure client side caching does not introduce problems when updating code.


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] [{module}] {asctime}: {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "/app/debug.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "DEBUG",  # Minimum level this logger will process
            "propagate": False,
        },
        "api": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "auth_app": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    "root": {  # Root logger for broader debugging
        "handlers": ["console"],
        "level": "DEBUG",
    },
}
